### ISSUE TITLE
Add led blm banner

### ISSUE THREAD

**Issue by yarikoptic** [datalad/ohbm-booth#2]
And lead to corresponding relevant resource. Could rotate with stop Police brutality

**Comment by yarikoptic** [comment]
See https://github.com/datalad/datalad/issues/4612 for police brutality. Need to create a resurrect url so if we manage to create datalad dataset for videos we could later redirect to it instead

**Comment by bpoldrack** [comment]
Hmm. I'm generally not too excited about getting somewhat political in such a booth.
Several reasons:

 - BLM stands for a sentence, a broader movement and an actual organization persuing/advocating specific policies (how they think the issue can and should be addressed). One can easily agree and support 1 and 2 while sincerely disagree with 3. That's leading to a certain ambiguity in what it really is, that "we" support. And how you read it pretty much depends on what you're reading in your daily "feeds" and therefore associating. Ambiguous message and unclear actual support of all the people involved, who are supposed to be represented by that booth.

 - general principle re politics: Don't think it's a good idea, that I (or anyone) need to support particular policies (or need to send that message at least), just because we are (enjoying to) work on those projects.

Not strongly opposing it in that case, but I'm not a fan of heading towards that direction.

How about being more specific? We could have the left top row section rotating w/ everything static but the left most screen in it. This one could rotate through "record" - "police" - "brutality" and we can link to that issue, pointing out how datalad can be of use or to those existing records or some redirect as you suggested.
Does that make sense?, @yarikoptic ?

**Comment by yarikoptic** [comment]
Yes: politicizing the booth is a touchy subject. We would need to agree. And also I would dislike promoting organizations which tactics we don't agree on. But I think we mustn't completely ignore existing societal problems and are in position to show support for what we all would agree to be right.
According to https://en.m.wikipedia.org/wiki/Black_Lives_Matter BLM , without organization, is about the movement, ie 1 and 2 . What about even making it with # to point to the topic, not any specific entity?
I also like rotating stop Police brutality.

**Comment by bpoldrack** [comment]
FTR: Made it a sequence consisting of "#BLM" -> "stop" -> "police" -> "brutality". Guess, that's sufficiently specific while not suggesting particular policies or sth.

Question remains, what to link. For now just made it a link to the datalad issue. Do you take care of that, @yarikoptic ?

**Comment by yarikoptic** [comment]
was done
